## SWIM Configuration
[FIELDS]
project_folder = '/home/dgketchum/PycharmProjects/swim-rs/examples/flynn'
fields_path = '/media/research/IrrigationGIS/swim/examples/flynn/gis/flynn_fields_sample.shp'

field_index = 'FID'

# Crop Coefficient Proxy
kc_proxy = 'etf'
cover_proxy = 'ndvi'

## Date Range
start_date = '2015-01-01'
end_date = '2020-12-31'

## Static file names
field_properties = '/media/research/IrrigationGIS/swim/examples/flynn/properties/flynn_sample_props.json'
input_timeseries = '/media/research/IrrigationGIS/swim/examples/flynn/input_timeseries/{}_daily.csv'
irrigation_data = '/media/research/IrrigationGIS/swim/examples/flynn/landsat/flynn_cuttings.json'

## Misc
elev_units = 'm'
refet_type = 'eto'

[CALIBRATION]
## PEST Calibration
calibrate_flag = 1
calibration_folder = '/home/dgketchum/PycharmProjects/swim-rs/examples/flynn/pest/mult'
# these must be ordered accoring to params.csv
calibrated_parameters = ['aw', 'ndvi_alpha', 'ndvi_beta', 'mad']

