## SWIM Configuration
[FIELDS]
project_folder = 'C:/Users/CND571/PycharmProjects/swim-rs/examples/tongue'

# data folder and alternate, so local and MCO machine paths get tried
data_folder = '/media/research/IrrigationGIS/swim'
alt_data_folder = 'C:/Users/CND571/Documents/Data/swim'

# fields data; prepend with data_folder
fields_path = 'examples/tongue/prepped_input/tongue_fields.json'

field_index = 'FID'

# Crop Coefficient Proxy
kc_proxy = 'etf'
cover_proxy = 'ndvi'

## Date Range
start_date = '2015-01-01'
end_date = '2020-12-31'

## Static file names; prepend with data_folder
input_data = 'examples/tongue/prepped_input/tongue_input.json'

## Misc
elev_units = 'm'
refet_type = 'eto'

[CALIBRATION]
## PEST Calibration
calibrate_flag = 1
calibration_folder = 'C:/Users/CND571/PycharmProjects/swim-rs/examples/tongue/master/mult'
initial_values_csv = 'C:/Users/CND571/PycharmProjects/swim-rs/examples/tongue/params.csv'

[RUNSPEC]
swb_mode = 'fao'
rew_ceff = 1.0
evap_ceff = 1.0
ro_reinf_frac = 0.0
winter_evap_limiter = 0.3
winter_end_day = 92
winter_start_day = 306
