## SWIM Configuration
[FIELDS]
project_folder = '/home/dgketchum/PycharmProjects/swim-rs/examples/tongue'
fields_path = '/media/research/IrrigationGIS/swim/examples/tongue/prepped_input/tongue_fields.json'

field_index = 'FID'

# Crop Coefficient Proxy
kc_proxy = 'etf'
cover_proxy = 'ndvi'

## Date Range
start_date = '2015-01-01'
end_date = '2020-12-31'

## Static file names
input_data = '/media/research/IrrigationGIS/swim/examples/tongue/prepped_input/tongue_input.json'

## Misc
elev_units = 'm'
refet_type = 'eto'

[CALIBRATION]
## PEST Calibration
calibrate_flag = 1
calibration_folder = '/home/dgketchum/PycharmProjects/swim-rs/examples/tongue/pest/mult'
initial_values_csv = '/home/dgketchum/PycharmProjects/swim-rs/examples/tongue/params.csv'

[RUNSPEC]
swb_mode = 'fao'
rew_ceff = 1.0
evap_ceff = 1.0
ro_reinf_frac = 0.0
winter_evap_limiter = 0.3
winter_end_day = 92
winter_start_day = 306
