## SWIM Configuration
[FIELDS]
project_folder = '/home/dgketchum/PycharmProjects/swim-rs/examples/flux'
fields_path = '/media/research/IrrigationGIS/swim/examples/flux/gis/flux_fields_sample.shp'

field_index = 'FID'

# Crop Coefficient Proxy
kc_proxy = 'etf'
cover_proxy = 'ndvi'

## Date Range
start_date = '2015-01-01'
end_date = '2020-12-31'

## Static file names
field_properties = '/media/research/IrrigationGIS/swim/examples/flux/properties/flux_sample_props.json'
input_timeseries = '/media/research/IrrigationGIS/swim/examples/flux/input_timeseries/{}_daily.csv'
irrigation_data = '/media/research/IrrigationGIS/swim/examples/flux/landsat/flux_cuttings.json'

## Misc
elev_units = 'm'
refet_type = 'eto'

[CALIBRATION]
## PEST Calibration
calibrate_flag = 1
calibration_folder = '/home/dgketchum/PycharmProjects/swim-rs/examples/flux/pest/mult'
# these must be ordered accoring to params.csv
calibrated_parameters = ['aw', 'rew', 'tew', 'ndvi_alpha', 'ndvi_beta', 'mad']

